# Generated by Django 5.2.7 on 2025-12-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], default='M', max_length=2, verbose_name='Giới tính'),
        ),
        migrations.AddField(
            model_name='member',
            name='ho',
            field=models.CharField(max_length=100, null=True, verbose_name='Họ'),
        ),
        migrations.AddField(
            model_name='member',
            name='ten',
            field=models.CharField(max_length=100, null=True, verbose_name='Tên'),
        ),
    ]
