# Generated by Django 5.2.7 on 2025-12-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_remove_member_email_remove_member_name_member_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='diem_cong',
        ),
        migrations.AddField(
            model_name='member',
            name='diem_cong_anh',
            field=models.IntegerField(default=0, verbose_name='Điểm cộng Anh'),
        ),
        migrations.AddField(
            model_name='member',
            name='diem_cong_van',
            field=models.IntegerField(default=0, verbose_name='Điểm cộng Văn'),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_id',
            field=models.IntegerField(max_length=6, unique=True, verbose_name='Mã số học sinh'),
        ),
    ]
