# Generated by Django 5.2.7 on 2025-12-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_remove_member_diem_cong_member_diem_cong_anh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], default='Nam', max_length=3, verbose_name='Giới tính'),
        ),
    ]
