# Generated by Django 5.2.7 on 2026-01-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_alter_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho', models.CharField(max_length=100, null=True, verbose_name='Họ')),
                ('ten', models.CharField(max_length=100, null=True, verbose_name='Tên')),
                ('student_id', models.IntegerField(max_length=6, unique=True, verbose_name='Mã số học sinh')),
                ('additional_english_points', models.IntegerField(default=0, verbose_name='Điểm cộng thêm Anh')),
                ('additional_literature_points', models.IntegerField(default=0, verbose_name='Điểm cộng thêm Văn')),
                ('reason', models.TextField(verbose_name='Lý do cập nhật điểm')),
            ],
        ),
    ]
