# Generated by Django 5.2.7 on 2026-01-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_updateplus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateplus',
            name='student_id',
            field=models.IntegerField(max_length=6, verbose_name='Mã số học sinh'),
        ),
    ]
